// Generated by CoffeeScript 1.6.3
(function() {
  var $, Dialog, EventEmitter, Items, err,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Dialog = require('modal-dialog');

  EventEmitter = require('events').EventEmitter;

  try {
    $ = require('$');
  } catch (_error) {
    err = _error;
    $ = window.jQuery;
  }

  Items = (function(_super) {
    __extends(Items, _super);

    Items.labels = {
      title: 'Items',
      addTypeHint: 'Add new type',
      removeType: 'Remove',
      okButton: 'OK',
      writeItem: 'Please enter new item for %s',
      removeItem: 'Remove',
      editItem: 'Edit',
      addItem: 'Add',
      help: 'There you can add new types. Just select it in menu above.'
    };

    Items.prototype.types = null;

    Items.prototype.initialized = false;

    Items.prototype.dialog = null;

    Items.prototype.defaults = null;

    Items.prototype.labels = null;

    Items.prototype.select = null;

    Items.prototype.resultElement = null;

    Items.prototype.summaryElement = null;

    function Items() {
      this.onSelectChange = __bind(this.onSelectChange, this);
      this.types = {};
      this.defaults = {};
      this.labels = {};
    }

    Items.prototype.prepare = function() {
      var header, item, items, name, _i, _len, _ref,
        _this = this;
      if (!this.initialized) {
        this.emit('beforeRender', this);
        this.prepareLabels();
        header = $('<div>', {
          html: $('<span>' + this.labels.title + '</span>')
        });
        this.select = $('<select>', {
          html: $('<option value="">' + this.labels.addTypeHint + '</option>'),
          change: this.onSelectChange
        });
        for (name in this.types) {
          this.addTypeToSelection(name);
        }
        this.select.appendTo(header);
        this.dialog = new Dialog;
        this.dialog.header = header;
        this.dialog.content = $('<div class="container"><div class="help">' + this.labels.help + '</div></div>');
        this.dialog.addButton(this.labels.okButton, function() {
          return _this.dialog.hide();
        });
        _ref = this.defaults;
        for (name in _ref) {
          items = _ref[name];
          if (items.length > 0) {
            this.addType(name);
            for (_i = 0, _len = items.length; _i < _len; _i++) {
              item = items[_i];
              this.addValue(name, item);
            }
          }
        }
        this.initialized = true;
        return this.emit('afterRender', this);
      }
    };

    Items.prototype.prepareLabels = function() {
      if (typeof this.labels.title === 'undefined') {
        this.labels.title = Items.labels.title;
      }
      if (typeof this.labels.addTypeHint === 'undefined') {
        this.labels.addTypeHint = Items.labels.addTypeHint;
      }
      if (typeof this.labels.removeType === 'undefined') {
        this.labels.removeType = Items.labels.removeType;
      }
      if (typeof this.labels.okButton === 'undefined') {
        this.labels.okButton = Items.labels.okButton;
      }
      if (typeof this.labels.writeItem === 'undefined') {
        this.labels.writeItem = Items.labels.writeItem;
      }
      if (typeof this.labels.removeItem === 'undefined') {
        this.labels.removeItem = Items.labels.removeItem;
      }
      if (typeof this.labels.editItem === 'undefined') {
        this.labels.editItem = Items.labels.editItem;
      }
      if (typeof this.labels.addItem === 'undefined') {
        this.labels.addItem = Items.labels.addItem;
      }
      if (typeof this.labels.help === 'undefined') {
        return this.labels.help = Items.labels.help;
      }
    };

    Items.prototype.open = function() {
      this.prepare();
      return this.dialog.show();
    };

    Items.prototype.close = function() {
      return this.dialog.hide();
    };

    Items.prototype.addTypeToSelection = function(name) {
      this.emit('registerType', name, this);
      return $('<option>', {
        value: name,
        html: this.types[name]
      }).appendTo(this.select);
    };

    Items.prototype.onSelectChange = function() {
      var selected;
      selected = this.select.find(':selected');
      return this.addType(selected.attr('value'), true);
    };

    Items.prototype.addType = function(name, autoAddValue) {
      var addButton, box, title,
        _this = this;
      if (autoAddValue == null) {
        autoAddValue = false;
      }
      title = $('<h3>', {
        html: this.types[name] + ' '
      });
      addButton = $('<a>', {
        href: '#',
        html: this.labels.addItem,
        click: function(e) {
          var msg, value;
          e.preventDefault();
          name = $(e.target).closest('div.type').attr('data-name');
          msg = _this.labels.writeItem.replace(/\%s/g, _this.types[name]);
          value = prompt(msg);
          if (value !== '' && value !== null) {
            return _this.addValue(name, value);
          }
        }
      }).appendTo(title);
      title.append(' ');
      $('<a>', {
        href: '#',
        html: this.labels.removeType,
        click: function(e) {
          e.preventDefault();
          return _this.removeType($(e.target).closest('div.type').attr('data-name'));
        }
      }).appendTo(title);
      box = $('<div>', {
        'class': 'type',
        html: title,
        'data-name': name
      });
      $('<ul></ul>').appendTo(box);
      box.appendTo(this.dialog.content);
      this.select.find('option[value=""]').prop('selected', true);
      this.select.find('option[value="' + name + '"]').remove();
      this.refreshOutputs();
      if (this.select.find('option').length === 1) {
        this.select.hide();
      }
      this.emit('addType', name, this);
      if (autoAddValue) {
        return addButton.click();
      }
    };

    Items.prototype.removeType = function(name) {
      this.dialog.content.find('div.type[data-name="' + name + '"]').remove();
      this.addTypeToSelection(name);
      if (this.select.is(':hidden')) {
        this.select.show();
      }
      this.refreshOutputs();
      return this.emit('removeType', name, this);
    };

    Items.prototype.addValue = function(type, value) {
      var item, list,
        _this = this;
      list = this.dialog.content.find('div.type[data-name="' + type + '"] ul');
      item = $('<li>', {
        html: $('<span>' + value + '</span>')
      });
      item.append(' ');
      $('<a>', {
        href: '#',
        html: this.labels.editItem,
        click: function(e) {
          var msg;
          e.preventDefault();
          msg = _this.labels.writeItem.replace(/\%s/g, _this.types[type]);
          value = prompt(msg, value);
          if (value !== '' && value !== null) {
            item.find('span').html(value);
            return _this.refreshOutputs();
          }
        }
      }).appendTo(item);
      item.append(' ');
      $('<a>', {
        href: '#',
        html: this.labels.removeItem,
        click: function(e) {
          e.preventDefault();
          item.remove();
          return _this.refreshOutputs();
        }
      }).appendTo(item);
      item.appendTo(list);
      this.refreshOutputs();
      return this.emit('addItem', type, value, this);
    };

    Items.prototype.getValues = function() {
      var result;
      result = {};
      this.dialog.content.find('div.type[data-name]').each(function(i, el) {
        var name;
        el = $(el);
        name = el.attr('data-name');
        if (el.find('ul li').length > 0) {
          result[name] = [];
          return el.find('ul li').each(function(i, li) {
            li = $(li);
            return result[name].push(li.find('span').html());
          });
        }
      });
      return result;
    };

    Items.prototype.setResultElement = function(el) {
      el = $(el);
      if (el.get(0).nodeName.toLowerCase() !== 'input' || el.attr('type') !== 'text') {
        throw new Error('Result: invalid element');
      }
      if (el.val() !== '') {
        this.defaults = JSON.parse(el.val());
      }
      return this.resultElement = el;
    };

    Items.prototype.setSummaryElement = function(el) {
      el = $(el);
      if (el.get(0).nodeName.toLowerCase() !== 'div') {
        throw new Error('Summary: invalid element');
      }
      el.append($('<ul>'));
      return this.summaryElement = el;
    };

    Items.prototype.refreshOutputs = function() {
      var item, items, list, name, type, ul, values, _i, _len;
      this.emit('beforeRefresh', this);
      values = this.getValues();
      if (this.resultElement !== null) {
        this.resultElement.val(JSON.stringify(values));
      }
      if (this.summaryElement !== null) {
        list = this.summaryElement.children('ul');
        list.html('');
        for (name in values) {
          items = values[name];
          type = $('<li>', {
            html: this.types[name]
          });
          if (items.length > 0) {
            ul = $('<ul>');
            for (_i = 0, _len = items.length; _i < _len; _i++) {
              item = items[_i];
              $('<li>' + item + '</li>').appendTo(ul);
            }
            ul.appendTo(type);
          }
          type.appendTo(list);
        }
      }
      return this.emit('afterRefresh', this);
    };

    return Items;

  })(EventEmitter);

  module.exports = Items;

}).call(this);
